### ISSUE TITLE
🏗️ [Core Feature]: Measure usage of the templates

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/polkadot-runtime-templates#203]
### What is the key feature we're aiming to implement?

We should have an easy way to know how many projects are using our templates and how. This will help us understand how we are doing and how people are using them.
We should at least have:
- How many projects are deploying to production with our templates.
- How many projects are deploying to testnet with our templates.
- What template they are using.

One way to measure it is by GH forks, but since we expect tools such as Pop CLI to be an important distribution channel those will not count as forks. One way we have discussed is by adding code to the generic template to emit an event that we can then index to track which template was used.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ozgunozerk** [comment]
Posting our progress and findings here for visibility.

After some research and getting ideas from Parity as well, the below seems like the best way to track usage:

### Adding our watermark to node's `properties` section:

The below snippet is from `chain_spec.rs`:

```rust
    properties.insert("tokenSymbol".into(), "UNIT".into());
    properties.insert("tokenDecimals".into(), 12.into());
    properties.insert("ss58Format".into(), 42.into());
    // add our watermark here
```

This will populate the `properties` section of the node, which is quite easy to query. Below is a snippet from `postman` on querying the `properties` field of the westend node:

<img width="355" alt="image" src="https://github.com/OpenZeppelin/polkadot-runtime-templates/assets/32795992/4fd38a22-9ecc-45f9-babb-29417febffec">

And lastly, below are the other options to track usage. We decided against them due to lack of simplicity and potential pollution to codebase:
- emitting and event (requires additional code, and potentially a new pallet)
- exposing a custom RPC (requires additional code, and potentially a new pallet)
- putting the watermark in `genesis_block` (requires additional code, harder to query than `properties`)

**Comment by ozgunozerk** [comment]
In polkadot.js.org/apps, we can see the `rpc` endpoints of the parachains.

After selecting a parachain on the left side: 
![telegram-cloud-photo-size-4-6003743301007687882-y](https://github.com/OpenZeppelin/polkadot-runtime-templates/assets/32795992/b2ed08ae-f085-4f38-b225-c1d5e66fcb79)

We can scroll down to see the rpc endpoint of the selected chain:
![telegram-cloud-photo-size-4-6003743301007687884-x](https://github.com/OpenZeppelin/polkadot-runtime-templates/assets/32795992/0739b099-6ccb-43cc-a92f-b829492ba091)

We can write a tool that automates this process to send rpc requests to all parachains out there to see which ones are using our template.
