### ISSUE TITLE
🎁 [Feature Request]: Pallet Abstractions to Improve DX

### ISSUE THREAD

**Issue by peektism** [OpenZeppelin/polkadot-runtime-templates#257]
### templates

- [X] Generic Runtime Template
- [X] Evm Template

Macros PR: https://github.com/OpenZeppelin/polkadot-runtime-wrappers/pull/1
Templates PR: https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/300

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by shawntabrizi** [comment]
@4meta5

Check out some of the ideas that @kianenigma has been working on

https://github.com/kianenigma/flite

In this example (at the time of writing), he has been able to create a wrapper around `frame_system` allowing us to define concrete types, and then use those concrete types inside a new pallet.

The example he gives is having `AccountId` represented concretely rather than with a generic type.

Ideally, we could expand this idea to also include within a single pallet things like Balances, and also a concrete balance type.

At that point, building a new pallet with Flite becomes trivial like a smart contract

**Comment by kianenigma** [comment]
Update on this: https://github.com/paritytech/polkadot-sdk/pull/5584

**Comment by kianenigma** [comment]
So I see that this is done, but in ways different from what I have proposed here. Can we discuss why? 

Note that I don't think there is something very wrong with what is currently done, but it lacks a few features: 

1. It is not type-safe: the macros are literally copy-pasting code around. There is still a point of synchronization where in `construct_runtime` all pallets need to be present. 
2. It is not using the power of Rust and its type system.

**Comment by ggonzalez94** [comment]
@kianenigma appreciate the feedback. As @4meta5 said we know this first iteration is far from perfect, but we hope it still is a significant improvement fro DevEx and simplifies the parachain runtime code.
I'll ping on Elements to find some time to sync this or next week if that works for you.
