### ISSUE TITLE
🐞 [Bug]: EVM Template Fails to Spawn with Zombienet

### ISSUE THREAD

**Issue by AlexD10S** [OpenZeppelin/polkadot-runtime-templates#289]
### templates

- [ ] Generic Runtime Template
- [X] Evm Template

### What happened?

I tried to spawn the network using Zombienet (and [pop](https://github.com/r0gue-io/pop-cli)) but I am getting the following error: 
```
Error:           Error: Command failed with exit code 1: bash -c ./target/release/evm-template-node build-spec --chain /var/folders/gz/2t0xjdgd2738_r1lb311drmr0000gn/T/zombie-3c8a69034ccef9d60ab6550b6840eee1_-23249-1Q1BjPHF5EKR/dev-1000-rococo-local-plain.json --disable-default-bootnode  --raw > /var/folders/gz/2t0xjdgd2738_r1lb311drmr0000gn/T/zombie-3c8a69034ccef9d60ab6550b6840eee1_-23249-1Q1BjPHF5EKR/dev-1000-rococo-local-raw.json
2024-08-16 14:06:04 Building chain spec    
Error: Service(Other("Invalid JSON blob: invalid length 48, expected a (both 0x-prefixed or not) hex string or byte array containing 20 bytes at line 1 column 1254"))
```

The Zombienet config file I am using is:
```toml
[relaychain]
chain = "rococo-local"
default_command = "./bin-v1.6.0/polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
addToGenesis = true
cumulus_based = true
chain = "dev"

[[parachains.collators]]
name = "collator01"
command = "./target/release/evm-template-node"
ws_port = 9933
rpc_port = 8833
args = ["--rpc-max-connections 10000"]

[[parachains.collators]]
name = "collator02"
ws_port = 9822
rpc_port = 8822
command = "./target/release/evm-template-node"
args = ["--rpc-max-connections 10000"]
```

 @ozgunozerk pointed me to the tutorial https://docs.openzeppelin.com/substrate-runtimes/2.0.0/guides/testing_with_zombienet  to run it manually, and it worked. However, when I try running it with Zombienet, it fails with the error mentioned above.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ozgunozerk** [comment]
We tried to debug this together with @AlexD10S, and here is another summary:

The error is happening when trying to create the `raw chain_spec` from `plain chain_spec`.
In other words, when chain specs are generated with manual commands (as represented in our guides), everything works. 
But if we rely on zombienet's internal commands for generating the chain_spec, then things go wrong.

The below situation suggests there is something wrong with our EVM template:
- pop cli evm template works when embedded into zombienet (collators present in the config file)
- our evm template doesn't work when embedded into zombienet (collators present in the config file)

However, the below situation suggests there is something wrong with zombienet's internal commands:
- our evm template work with zombienet (different terminal instances for node, and zombienet)

We will investigate it further to determine whether it is caused by our template or zombienet. My initial guess is something is wrong on zombienet's internal commands for generating the chain_spec

**Comment by ozgunozerk** [comment]
Plain chain spec generated by manual commands:
![telegram-cloud-photo-size-4-5906578290230019683-y](https://github.com/user-attachments/assets/7839935c-9e37-4cdb-8943-737ff06ae552)


Plain chain spec generated by zombienet:
![telegram-cloud-photo-size-4-5906578290230019684-y](https://github.com/user-attachments/assets/af44aa0e-6b79-499c-8d87-7d294f478546)

**Comment by ozgunozerk** [comment]
@AlexD10S discovered that this problem is related to zombienet not supporting `AccountId20`. 
Pop-cli evm template uses `AccountId32`, so all the mystery seems to be resolved. 

Here is the relevant issue:
https://github.com/paritytech/zombienet/issues/1826
