### ISSUE TITLE
Ensure CI catches WASM compilation errors

### ISSUE THREAD

**Issue by peektism** [OpenZeppelin/polkadot-runtime-templates#99]
> _Originally posted by @ozgunozerk in https://github.com/OpenZeppelin/polkadot-runtime-template/issues/95#issuecomment-1883090155_

#95 shows that the CI is still not catching errors related to failing WASM compilation

Any PR to fix the CI to enforce WASM compilation correctly should consider making a temporary branch and reverting #95 on that branch to check that the CI correctly catches this error.

**Comment by ozgunozerk** [comment]
The weird thing is about this is:
- the CI does not fail (ubuntu latest and macos)
- my machine does not fail (macos with m1)
- it fails on Amar's machine (@4meta5 can you fill here? )

Maybe it's a deeper issue related to substrate code, don't know for sure. Maybe CI was correct all along, and the issue was emerging on some edge case. Needs more inspection

**Comment by ozgunozerk** [comment]
> We had previously agreed in https://github.com/OpenZeppelin/polkadot-runtime-template/pull/95 that the error was real and the CI did not catch it.

I don't recall that. I'm saying that the error being real is very likely, but still not 100%. Please see my above comment. It is strange to not be able to replicate this in 3 machines, but only in 1.

I'm not saying the issue is not real, I'm saying we need to further investigate it. 

Could you please share the specifics of your local machine for this?

**Comment by ozgunozerk** [comment]
discussed in a meeting, @4meta5 will figure out a way to make this issue reproducible (maybe a docker container, etc.). Till then, keeping this issue open
